- name: k8 deployment process
       hosts: localhost
       remote_user: root
       become: root

       tasks:
          - name: git clone
             git:
                repo:  ‘https://github.com/suvarchalak/techtest.git'
                dest:  /tmp/techtest

          -  name: execute commands
              command:  “{{item}}”
              with_items:
                     - cd /tmp/tectest
                     - kubectl apply -f  postgres-configmap.yaml
                     - kubectl apply -f redis-deployment.yaml
                     - kubectl apply -f postures-deployment.yaml
                     - kubectl apply -f postures-service.yaml
                     - kubectl apply -f postures-storage.yaml
                     - apply
