apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: bala4352/repo:devops-app  # or just image: redis
        env:
        - name:  DB_HOST
          value: db
        - name:  DB_USER
          value: postgresadmin
        - name:  DB_PASSWORD
          value: admin123
        - name:  DB_NAME
          value: postgresdb
        - name:  REDIS_URL
          value: redis://redis:6379/
        - name:  WAIT_FOR
          value: 'db:5432 redis:6379'
        ports:
        - containerPort: 8080

